djangoDemoProject/demoProject/demoApp/urls.py
import email
from unicodedata import name
from django.contrib.auth import login, views as auth_views
from django.urls import path
from . import views

# from django.views.generic import TemplateView
app_name = 'demoApp'

urlpatterns = [
    path('',views.HomepageView.as_view(),name='home'),
    path('signup1/',views.SignUpView.getUser,name='signup1'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login1/',views.LoginCheckView.check_login,name= 'login1'),
    path('index/',views.AfterLoginView.as_view(), name='index'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('forgetPassword/',views.ForgetPasswordView.as_view(), name = 'forgetPassword'),
    path('getlink/',views.ForgetPasswordView.get_link,name='getlink'),
    path('resetpassword/',views.ResetPasswordView.after_reset_Password,name='resetpassword'),
    path('DetailPage/<int:id>/',views.GetDetail,name="detail"),
    path('resetPasswordLink/<token>/<email>',views.ResetPasswordView.resetPassord, name ='resetPasswordLink'),
    path('logout/',views.Logout,name="logout"),
    path('addDetails/',views.AddDetailsView.add_details, name='addDetails'),
    path('addDetailsPage/',views.AddDetailsView.as_view(), name='addDetailsPage'),
    path('delete/<int:id>/',views.delete_record, name = 'delete'),
    path('edit/<int:id>/',views.edit_record, name = 'edit'),
    path('update/<int:ma_id>/<int:m_id>/<int:a_id>/<int:g_id>/',views.update_record, name = 'updateDetails')
    
]

djangoDemoProject/demoProject/demoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('demoApp.urls')),
    path('', include('demoApp.urls', namespace='demoApp')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoDemoProject/demoProject/demoApp/models.py
# from os import access
from datetime import timedelta
from email.policy import default
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20, null= True)

    def __str__(self):
        return self.name 

class Movie(models.Model):
    title = models.CharField(max_length=50)
    language = models.CharField(max_length=20, blank = False)
    duration = models.DurationField(default=timedelta())
    release = models.DateField()
    country = models.CharField(max_length=20)
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    image = models.ImageField(default = "", upload_to="image/")
    def __str__(self):
        return self.title
class Artist(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class MovieArtist(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    artist  = models.ForeignKey(Artist, on_delete=models.CASCADE)
    a_typeChoice = (
        ("actor", "actor"),
        ("director", "director"),
        ("producer", "producer"),
    )
    a_type = models.CharField(max_length=20, choices=a_typeChoice)
    def __str__(self):
        return self.a_type

class User(AbstractBaseUser):
    
    
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    mobile = models.CharField(max_length=13, unique=True)
    password = models.CharField(max_length=200, null= False, blank= False)
    confirm_password = models.CharField(max_length=200, null = False, blank= False)
    username = None
    email = models.EmailField(unique=True) 
    is_superuser = models.BooleanField(default = False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    

djangoDemoProject/demoProject/demoApp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms 
class UserCreateForm(UserCreationForm):
    class Meta():
        fields = ('firstname','lastname', 'email','mobile', 'password', 'confirm_password')
        model = User
    
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['username'].label= 'Display Name'
#         self.fields['username'].label = 'Email Address'

class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ("email","password")

djangoDemoProject/demoProject/demoApp/views.py
# from django.contrib.auth.forms import UsernameField
# from . import forms
from datetime import timedelta
from django.views import View
from pyexpat.errors import messages
import uuid
from django.contrib.auth.hashers import make_password
from django.views.generic import TemplateView
from .models import Artist, Genre, Movie, MovieArtist, User
from django.shortcuts import render, redirect
from .forms import UserCreateForm, UserForm
from .emailSetup import forget_password_mail
from .backends import CustomBackend
from django.contrib.auth import authenticate


class SignUpView(TemplateView):       
    form_class = UserCreateForm
    template_name = "signup.html"
    def getUser(request):
        if request.method=='POST':
            userData = User(
                firstname = request.POST.get('fname'),
                lastname = request.POST.get('lname'),       
                email = request.POST.get('email'),
                mobile = request.POST.get('mobile'),
                password = make_password(request.POST.get('psw')),
                confirm_password = make_password(request.POST.get('psw-repeat'))
            )
            # userData.is_superuser=True
            userData.save()
            return render(request, 'login.html')
        


class LoginCheckView(TemplateView):
    form_class = UserForm
    # template_name = 'login.html'   
       
    def check_login(request):
        user = ''
        if request.method == 'POST':
            login_user = request.POST.get('uname')
            login_password = request.POST.get('psw')
            try:
                user = authenticate(request, email =  login_user, password = login_password)
            except Exception as e:
                return render(request, 'login.html')
            request.session['user'] = user.id
            if user.is_superuser:
                request.session['is_superuser'] = True
                return redirect('demoApp:home',)
            else:
                return redirect('demoApp:home')

class ForgetPasswordView(TemplateView):

    template_name = 'forget_password.html'
    def get_link(request):
        token = str(uuid.uuid4())
        if request.method == 'POST':
            email = request.POST.get('uname')
            print('email_valid:',email)
            
            # global Email
            # Email = email  
            try:
                user = User.objects.get(email=email)  
            except:
                pass
            data = {"email":email}  
            if email == user.email:
                forget_password_mail(email, token)
                Email = email
                return render(request, 'forget_password.html', data)
            else:
                return messages.success(request, 'User not found with this username')

class ResetPasswordView(ForgetPasswordView, TemplateView):
    def resetPassord(request, token, email):
        return render(request, 'reset_password.html',{'newEmail':email})
    def after_reset_Password(request):
        
        if request.method == 'POST':
            try:
                userData = User.objects.get(email=request.POST.get('email'))
                password = request.POST.get('psw')
                confirm_password =request.POST.get('cpsw')                
                if password == confirm_password:
                    userData.password = make_password(password)
                    userData.confirm_password = make_password(confirm_password)
                    userData.save()
                    return render(request, 'login.html')
                else:
                    return render(request, 'reset_password.html', {'message':"password not match"})  

            except:
                pass
            
                
class HomepageView(TemplateView):
    template_name = "homepage.html"
    def get(self, request):
        genre = Genre.objects.all()
        movie = Movie.objects.all()
        movie_artist = MovieArtist.objects.all()
        artist = Artist.objects.all()
        return render(request, 'homepage.html', {"movie":movie, "movie_artist":movie_artist, "artist":artist,"genre":genre})
       
class AfterLoginView(View):
    def get(self, request):
        dict = {}
        genre = Genre.objects.all()
        movie = Movie.objects.all()
        movie_artist = MovieArtist.objects.all()
        artist = Artist.objects.all()
        dict = {"movie":movie, "movie_artist":movie_artist, "artist":artist, "genre":genre}
        return render(request, 'index.html', {"movie":movie, "movie_artist":movie_artist, "artist":artist,"genre":genre})
       
def GetDetail(request,id):
    if request.session.get('user'):
        data = MovieArtist.objects.get(pk=id)
        return render(request,'index.html',{'movie_artist':data})
    else:
        return render(request,'login.html',{'message':"Please Login First"})

def Logout(request):
    request.session.clear()
    return redirect("/")

class AddDetailsView(TemplateView):
    template_name = 'addData.html'
    def add_details(request):
        if request.method == 'POST':
            duration = request.POST.get('duration')
            duration = duration.split(':') 
            AddGenreDetails = Genre(
                name = request.POST.get('genre')
            )            
            AddGenreDetails.save()
            AddMovieDetails = Movie(
                title = request.POST.get('title'),
                language = request.POST.get('language'),
                duration = timedelta(hours = int(duration[0]),minutes= int(duration[1])),
                release = request.POST.get('release'),
                country = request.POST.get('country'),
                description = request.POST.get('description'),
                genre = AddGenreDetails,
                image = request.FILES['img']
            )
            AddMovieDetails.save()
            AddArtistDetails = Artist(
                name = request.POST.get('artist')
            )
            AddArtistDetails.save()
            AddMovieArtistDetails = MovieArtist(
                a_type = request.POST.get('artist type'),
                movie = AddMovieDetails,
                artist = AddArtistDetails
            )
            AddMovieArtistDetails.save()
            
        return redirect('demoApp:home')
class DeleteRecord(TemplateView):
    pass
def delete_record(request, id):
    record = MovieArtist.objects.get(pk=id)
    record.delete()
    return redirect('demoApp:home')

def edit_record(request, id):
    record = MovieArtist.objects.get(pk=id)
    print(record.movie.description)
    return render(request, 'edit.html', {'data':record})

def update_record(request, ma_id, m_id, a_id, g_id):
    duration = request.POST.get('duration')
    duration = duration.split(':') 
    AddGenreDetails = Genre.objects.get(pk=g_id)
    AddGenreDetails.name = request.POST.get('genre')          
    AddGenreDetails.save()

    AddMovieDetails = Movie.objects.get(pk=m_id)
    AddMovieDetails.title = request.POST.get('title')
    AddMovieDetails.language = request.POST.get('language')
    AddMovieDetails.duration = timedelta(hours = int(duration[0]),minutes= int(duration[1]))
    AddMovieDetails.release = request.POST.get('release')
    AddMovieDetails.country = request.POST.get('country')
    AddMovieDetails.description = request.POST.get('description')
    AddMovieDetails.genre = AddGenreDetails
    AddMovieDetails.image = request.FILES['img']
    
    AddMovieDetails.save()
    AddArtistDetails = Artist.objects.get(pk=a_id)
    AddArtistDetails.name = request.POST.get('artist')
    AddArtistDetails.save()

    AddMovieArtistDetails = MovieArtist.objects.get(pk=ma_id)
    AddMovieArtistDetails.a_type = request.POST.get('artist type')
    AddMovieArtistDetails.movie = AddMovieDetails
    AddMovieArtistDetails.artist = AddArtistDetails
    AddMovieArtistDetails.save()
    
    return redirect('demoApp:home')

djangoDemoProject/demoProject/demoApp/templates/addData.html
{% block content %}
<form method="POST" action = "{% url 'demoApp:addDetails' %}" enctype="multipart/form-data">
    <div class="container">
      
      {% csrf_token %}
      
      <center>
        <h1>add details</h1>
      <label for="title"><b>title</b></label>
      <input type="text" placeholder="Enter title" name="title" id="title" required><br><br>
        
      <label for="language"><b>language</b></label>
      <input type="text" placeholder="language" name="language" id="language" required><br><br>
      
      <label for="duration"><b>duration</b></label>
      <input type="time" placeholder="duration" name="duration" id="duration" required><br><br>
      
      <label for="release"><b>release date</b>
        <input type="date" name="release" required pattern="\d{2}-\d{2}-\d{4}">
      </label><br><br>
      
      <label for="country"><b>country</b></label>
      <input type="text" placeholder="country" name="country" id="country" required><br><br>
      
      <label for="genre"><b>genre</b></label>
      <input type="text" placeholder="genre" name="genre" id="genre" required><br><br>
      
      <label for="artist"><b>artist</b></label>
      <input type="text" placeholder="artist" name="artist" id="artist" required><br><br>

      <label for="artist type"><b>artist type</b></label>
      <input type="text" placeholder="artist type" name="artist type" id="artist type" required><br><br>

      <label for="img"><b>Select image:</b></label>
      <input type="file" id="img" name="img" accept="image/*"><br><br>

      <p class="q"><b>description</b></p>
      <textarea id="text1" name="description" rows="5" cols="50" required></textarea><br><br>
      
      <button type="submit" class="registerbtn">add</button>
    
    </div>
  </form>
  {% endblock %}

djangoDemoProject/demoProject/demoApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% comment %} {% load staticfiles %} {% endcomment %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MovieApp</title>
    <style>  
        a{  
            text-decoration: none;  
            color: green;  
            font-size: 20px;  
            padding : 8px;  
            text-align: center;  
        }  
        a:hover{  
            color: blue;  
        }  
             h1{  
        text-align: center;  
        }  
    </style>  
</head>
<body>
    {% comment %} {% block content %} {% endcomment %}
    {% comment %} <div> {% endcomment %}
    <nav class="navbar mynav" role='navigation' id='navbar'>
        <div class="container">
            {% comment %} {% block homepage %} {% endcomment %}
            <a class ='navbar-brand mynav' href="{% url 'demoApp:home' %}">MovieApp</a>
            
            {% comment %} <a class ='navbar-brand mynav' href="{% url 'demoApp:home' %}">MovieApp</a> {% endcomment %}
            
            <ul class = "nav navbar-nav navbar-right">
                {% comment %} {{request.session.is_superuser}} {% endcomment %}
                {% if request.session.user%}
                    <li><a href="{% url 'demoApp:logout' %}">Log Out</a></li>
                
                    {% if request.session.is_superuser %}
                        <li><a href="{% url 'demoApp:addDetailsPage' %}" >Add</a></li>
                        {%endif%}

                {% else %}
                    <li><a href="{% url 'demoApp:login' %}" >Log in</a></li>
                    <li><a href="{% url 'demoApp:signup' %}" >Sign up</a></li>
                {% endif %}
            </ul>
           
            {% comment %} {% endblock %} {% endcomment %}
        </div>
    </nav>
{% comment %} </div> {% endcomment %}
<div class="container mycontent">
    {% block content %} 

    {% endblock %}

  </div>
{% comment %} {% endblock %} {% endcomment %}
</body>
</html>

djangoDemoProject/demoProject/demoApp/templates/details.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/demoApp/static/style.css">
</head>

<body>
    <h1>{{request.session.is_superuser}}</h1>
    {% for data in movie_artist%}
    <div>
        <ul><h2><p>title: </p>{{data.movie.title}}</h2></ul>
        <ul><p><p>language: </p>{{data.movie.language}}</p></ul>
        <ul><p><p>duration: </p>{{data.movie.duration}}</p></ul>
        <ul><p><p>release: </p>{{data.movie.release}}</p></ul>
        <ul><p><p>country: </p>{{data.movie.country}}</p></ul>
        <ul><p><p>description: </p>{{data.movie.description}}</p></ul>
        <ul><p><p>genre: </p>{{data.movie.genre.name}}</p></ul>
        <ul><p><p>artist: </p>{{data.artist.name}}</p></ul>
        <ul><p><p>artist type: </p>{{data.a_type}}</p></ul>  
        
    </div>
    {%endfor%} 
</body>
</html>
{% endblock content %}

djangoDemoProject/demoProject/demoApp/templates/edit.html
{% block content %}
<form method="POST" action = "{% url 'demoApp:updateDetails' data.id data.movie.id data.artist.id data.movie.genre.id %}" enctype="multipart/form-data">
    <div class="container">
      
      {% csrf_token %}
      
      <center>
        <h1>add details</h1>
      <label for="title"><b>title</b></label>
<input type="text" placeholder="Enter title" value="{{data.movie.title}}" name="title" id="title" required><br><br>
        
      <label for="language"><b>language</b></label>
      <input type="text" placeholder="language" value="{{data.movie.language}}" name="language" id="language" required><br><br>
      
      <label for="duration"><b>duration</b></label>
      <input type="time" placeholder="duration" value="{{data.movie.duration}}" name="duration" id="duration" required><br><br>
      
      <label for="release"><b>release date</b>
        <input type="date" name="release" value="{{data.movie.release}}" required pattern="\d{2}-\d{2}-\d{4}">
      </label><br><br>
      
      <label for="country"><b>country</b></label>
      <input type="text" placeholder="country" value="{{data.movie.country}}" name="country" id="country" required><br><br>
      
      <label for="genre"><b>genre</b></label>
      <input type="text" placeholder="genre" value="{{data.movie.genre.name}}" name="genre" id="genre" required><br><br>
      
      <label for="artist"><b>artist</b></label>
      <input type="text" placeholder="artist" value="{{data.artist.name}}"name="artist" id="artist" required><br><br>

      <label for="artist type"><b>artist type</b></label>
      <input type="text" placeholder="artist type" value="{{data.a_type}}" name="artist type" id="artist type" required><br><br>

      <label for="img"><b>Select image:</b></label>
      <input type="file" id="img" name="img" accept="image/*"><br><br>

      <p class="q"><b>description</b></p>
      <textarea id="text" name="description" value="{{data.movie.description}}" rows="5" cols="50" required></textarea><br><br>
      
      <button type="submit" class="primary-btn">update</button>
    
    </div>
  </form>
  {% endblock %}

djangoDemoProject/demoProject/demoApp/templates/forget_password.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie</title>
    <style>
        .center {
  margin: auto;
  width: 60%;
  border: 3px solid #73AD21;
  padding: 10px;}
    </style>
</head>
<body>
    <form method="POST" action = "{% url 'demoApp:getlink' %}" >
        {% csrf_token %}
    <div class="container">
        <center><label for="uname"><b>Username</b></label>
            <input type="text" placeholder="Enter Email" name="uname" required><br><br>
            <button type="submit">Get Link</button><br><br>
        </center>
        
    </div>
</body>
</html>
{% endblock %}

djangoDemoProject/demoProject/demoApp/templates/homepage.html
{% extends "base.html" %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="/demoApp/static/style.css">
    </head>
    <body>
        <div style="display:grid; grid-template-columns: auto auto auto auto auto; gap: 20px;">
        {% for data in movie_artist%}
        <div>
            <img src={{data.movie.image.url}} alt="Avatar" style="width:200px; height : 300px" >
            <div class="container">
                <a href="{% url 'demoApp:detail' data.id %}"><h4><b>{{data.movie.title}}</b></h4> </a>
                
            
            
        </div>
        </div>
        {%endfor%} 
        </div>
    </body>
    </html>
    <!-- <h1>Welcome to Movie App!</h1>
    <center><h2>Login or Sign-up to get started!</h2></center> -->
    
    </body>
{% endblock content %}

djangoDemoProject/demoProject/demoApp/templates/index.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        div{display:inline-block;}
    </style>
</head>

<body>
    <h1></h1>
    
    <div>
        <ul><h2>{{movie_artist.movie.title}}</h2></ul>
        <ul><p>{{movie_artist.movie.language}}</p></ul>
        <ul><p>{{movie_artist.movie.duration}}</p></ul>
        <ul><p>{{movie_artist.movie.release}}</p></ul>
        <ul><p>{{movie_artist.movie.country}}</p></ul>
        <ul><p>{{movie_artist.movie.description}}</p></ul>
        <ul><p>{{movie_artist.movie.genre.name}}</p></ul>
        <ul><p>{{movie_artist.artist.name}}</p></ul>
        <ul><p>{{movie_artist.a_type}}</p></ul> 
        {% if request.session.is_superuser %} 
                <a href="{% url 'demoApp:edit' movie_artist.id %}" >Edit</a>
                <a href="{% url 'demoApp:delete' movie_artist.id %}" >Delete</a>   
        {% endif %}     
    </div>
     
</body>
</html>
{% endblock content %}

djangoDemoProject/demoProject/demoApp/templates/login.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <title>Document</title> -->
    {% comment %} <style>
        * {
           text-align: center;
            
        }
        </style> {% endcomment %}
        <!-- <style>
          body{
                background-color: #f1f1f1;
          }
          </style> -->
          {% if message %}
          <script>
              alert("{{message}}")
          </script>
          {% endif %}
</head>

<body>
    
      <center>
        
        <h2>Login to Movie Database</h2>
        
        <!-- <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button> -->
        
        <div  class="modal" id="">
          
          <form method="POST" action = "{% url 'demoApp:login1' %}" >
            {% csrf_token %}

            <div class="imgcontainer">
              <!-- <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span> -->
              <!-- <img src="img_avatar2.png" alt="Avatar" class="avatar"> -->
            </div>
        
            <div class="container">
              <label for="uname"><b>Username</b></label>
              <input type="text" placeholder="Enter Username" name="uname" ><br><br>
        
              <label for="psw"><b>Password</b></label>
              <input type="password" placeholder="Enter Password" name="psw" ><br><br>
                
              <button type="submit">Login</button><br><br>
              <!-- <label>
                <input type="checkbox" checked="checked" name="remember"> Remember me
              </label><br><br> -->
            </div>
        
            <div class="container">
              <!-- <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button> -->
              <span class="psw"> <a href="{% url 'demoApp:forgetPassword' %}">Forgot Password?</a></span>
            </div>
          </form>
        </div>
        
        
      </center>
 
    {% endblock %}
    
</body>
</html>

djangoDemoProject/demoProject/demoApp/templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
           text-align: center;
            
        }
        </style>
</head>

<body>
    {% block content %}

        
        {% if message %}
            <script>
                alert("password not match")
            </script>
        {% endif %}
        <!-- <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button> -->
        
        <div  class="modal" id="">
          
          <form method="POST" action = "{% url 'demoApp:resetpassword' %}" >
            {% csrf_token %}
            <input hidden value="{{newEmail}}" type="text" placeholder="Enter Username" name="email" required><br><br>
            <h2>Reset Password</h2>
            <div class="imgcontainer">
              <!-- <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span> -->
              <!-- <img src="img_avatar2.png" alt="Avatar" class="avatar"> -->
            </div>
        
            <div class="container">

              <label for="uname"><b>Password</b></label>
              <input type="text" placeholder="Enter Username" name="psw" required><br><br>
                            
              <label for="psw"><b>Confirm Password</b></label>
              <input type="password" placeholder="Enter Password" name="cpsw" required><br><br>
                <!-- <input type="text" value="{{ email }}"> -->
              <button type="submit">Submit</button><br><br>
              <!-- <label>
                <input type="checkbox" checked="checked" name="remember"> Remember me
              </label><br><br> -->
            </div>
        
            <div class="container" style="background-color:#f1f1f1">
            
            </div>
          </form>
        </div>
        
        <!-- <script>
        // Get the modal
        var modal = document.getElementById('id01');
        
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
        </script> -->
        
    {% endblock content%}
    
</body>
</html>

djangoDemoProject/demoProject/demoApp/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  
</style>
</head>
<body>

<form method="POST" action = "{% url 'demoApp:signup1' %}">
  <div class="container">
    {% csrf_token %}
    <h1>Register</h1>
    <!-- <hr> -->
    <center>
    <label for="email"><b>First Name</b></label>
    <input type="text" placeholder="Enter First Name" name="fname" id="fname" required><br><br>
	  
    <label for="email"><b>Last Name</b></label>
    <input type="text" placeholder="Enter Last Name" name="lname" id="lname" required><br><br>
	
    <label for="email">&ensp;&nbsp;<b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="email" required><br><br>
    
    <label for="email"><b>Mobile Number</b></label>
    <input type="text" placeholder="Enter Mobile Number" name="mobile" id="mobile" required><br><br>
    
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" id="psw" required><br><br>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required><br><br>
    <!-- <hr> -->
    {% comment %} <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p> {% endcomment %}

    <button type="submit" class="registerbtn">Register</button>
  </div>
  
  <div class="container Lod in">
    <!-- <p>Already have an account? please Log in</p> -->
  </div>
</form>
</center>
</body>
</html>

{% endblock content %}